[supervisord]
nodaemon=true
user=root

[program:nginx]
command=sh /app/infra/nginx-wrapper.sh
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:backend]
command=sh -c "cd /app/backend && node dist/index.js"
autostart=true
autorestart=true
directory=/app/backend
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true

[program:bot]
command=node /app/bot/dist/index.js
autostart=true
autorestart=true
directory=/app/bot
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
